# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c8f33c6766aa97c72ae68e7ab5e563e20aa8803e1285b18d15579ea4b2794799f4ab693b128d04fd3be9a185ec2450cefa8d41ebff2940f2aa6a60826a70e2

test:
  secret_key_base: 9916358b4c86b01d230d0be81e0ea804739e336b3d65a1c3a5ec72e2838b5b98bcb903c9509f4f0bf39584fe9640dbb64a874ec2f30da24e31e592b7b97f4922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
